### ISSUE TITLE
NitroModules integration fails: "Could not build Objective-C module 'AudioRecorderPlayer'" with    nitro.json configuration mismatch

### ISSUE THREAD

**Issue by varungandhi121** [hyochan/react-native-audio-recorder-player#675]
<img width="392" height="358" alt="Image" src="https://github.com/user-attachments/assets/56ab8d34-d2ff-4f67-894e-ffb4f5223744" />

### Before submitting a new issue

- [ ] I tested using the latest version of the library, as the bug might be already fixed.
- [ ] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [x] I checked for possible duplicate issues, with possible answers.

### Bug summary

  The library fails to build on iOS when using NitroModules integration due to:
  1. Configuration mismatch in nitro.json between iosModuleName and androidCxxLibName
  2. Missing Objective-C module build for AudioRecorderPlayer
  3. JSI module compilation errors
  4. Missing folly/experimental/coro/Coroutine.h file

### Library version

  4.2.1

### Project type

React Native (bare workflow)

### React Native version

0.76.5

### Environment info

```shell
System:
  OS: macOS 15.5
  CPU: (8) arm64 Apple M2
  Memory: 105.75 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.15.1
    path: ~/.nvm/versions/node/v20.15.1/bin/node
  Yarn: Not Found
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v20.15.1/bin/npm
  Watchman:
    version: 2025.02.17.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/varungandhi-digiqc/.rvm/gems/ruby-3.1.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.5
      - iOS 18.5
      - macOS 15.5
      - tvOS 18.5
      - visionOS 2.5
      - watchOS 11.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.3 AI-243.22562.218.2431.13114758
  Xcode:
    version: 16.4/16F6
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.14
    path: /usr/bin/javac
  Ruby:
    version: 3.1.0
    path: /Users/varungandhi-digiqc/.rvm/rubies/ruby-3.1.0/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.5
    wanted: 0.76.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Steps to reproduce

1. Install react-native-audio-recorder-player@4.2.1 in React Native 0.76.5 project
  2. Enable New Architecture (RCT_NEW_ARCH_ENABLED = '1' in Podfile)
  3. Configure Podfile with:
  use_frameworks! :linkage => :static
  use_react_native!(:fabric_enabled => true, :hermes_enabled => true)
  4. Run cd ios && pod install
  5. Attempt to build iOS project1.

### Reproducible example repository

 Title:   NitroModules integration fails: "Could not build Objective-C module 'AudioRecorderPlayer'" with   nitro.json configuration mismatch    Bug summary:   The library fails to build on iOS when using NitroModules integration due to configuration   mismatch in nitro.json between iosModuleName and androidCxxLibName, causing Objective-C module   build failures and JSI compilation errors.    Library version:   4.2.1    Project type:   React Native CLI    React Native version:   0.76.5    Steps to reproduce:   1. Create React Native 0.76.5 project with New Architecture enabled   2. Install react-native-audio-recorder-player@4.2.1   3. Configure Podfile with: use_frameworks! :linkage => :static, fabric_enabled: true,   hermes_enabled: true   4. Run cd ios && pod install   5. Run npx nitro-codegen (fails with configuration mismatch error)   6. Attempt to build iOS project (fails with Objective-C module errors)

HERE IS MY PODFILE::
min_ios_version_supported = '16.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Add default CocoaPods source
source 'https://cdn.cocoapods.org/'

ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

setup_permissions([
  'Camera',
  'LocationAlways',
  'LocationWhenInUse',
  'MediaLibrary',
  'Microphone',
])

# Force static linking (required for VisionCamera and some JSI-based modules)
use_frameworks! :linkage => :static

# Define React Native path
react_native_path = "../node_modules/react-native"

target 'digiQCV2' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :fabric_enabled => true,
    :hermes_enabled => true # ✅ Ensure Hermes for JSI modules
  )

  # ✅ Add Folly for JSI-based modules (e.g., NitroModules)
  pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'

  # JSI, ReactCommon, and Yoga are automatically included by use_react_native!

  pod 'SDWebImage'
  pod 'SDWebImageWebPCoder'

  # Firebase pods (optional)
  # pod 'Firebase', :modular_headers => true
  # pod 'FirebaseCoreInternal', :modular_headers => true
  # pod 'GoogleUtilities', :modular_headers => true
  # pod 'FirebaseCore', :modular_headers => true
  # pod 'FirebaseInstallations', :modular_headers => true
  # pod 'GoogleDataTransport', :modular_headers => true
  # pod 'nanopb', :modular_headers => true
  # pod 'FirebaseABTesting', :modular_headers => true
  # pod 'FirebaseCoreExtension', :modular_headers => true

  target 'digiQCV2Tests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # ✅ Fix for M1/M2 Simulator compatibility
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64' if RUBY_PLATFORM.include?('darwin')

        # ✅ Minimum version override for OneSignal or other pods
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 15.1
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        end
      end
    end
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '5.2.14'
end

**Comment by varungandhi121** [comment]
Hey anyone face this issue ?Please help me.

**Comment by equilizer** [comment]
faceing the same issue

**Comment by sougatamanna98** [comment]
I am facing same issue in iOS

**Comment by akinbasaran** [comment]
I had the same problem. As long as I used use_frameworks! :linkage => :static there was no solution. Finally I had to remove the library. I tried a lot but couldn't find a solution.

**Comment by hyochan** [comment]
Could you please provide a reproducible example so I can dig into the issue?
Also, could you try running the example project that's set up with a Yarn workspace in the repo?
Please check the [CONTRIBUTING.md](https://github.com/hyochan/react-native-audio-recorder-player/blob/main/CONTRIBUTING.md) file to learn how to run the example app.

**Comment by akinbasaran** [comment]
When I create a new project with React Native 0.80 and load the library, it works without any problems. However, when I load a library that requires "use_frameworks! :linkage => :static", such as React Native Firebase, it does not work. When I use "use_frameworks! :linkage => :static", I get the error as above. Despite all my attempts, I couldn't solve it.

**Comment by hyochan** [comment]
> When I create a new project with React Native 0.80 and load the library, it works without any problems. However, when I load a library that requires "use_frameworks! :linkage => :static", such as React Native Firebase, it does not work. When I use "use_frameworks! :linkage => :static", I get the error as above. Despite all my attempts, I couldn't solve it.

Thank you for this info! This is very helpful.
Do you think that this could solve the issue? https://github.com/hyochan/react-native-audio-recorder-player/pull/676#issuecomment-3164984212

**Comment by mushthak02** [comment]
same issue

**Comment by varungandhi121** [comment]
✅ Temporary Workaround

I was facing the same issue while using react-native-audio-recorder-player with NitroModules and New Architecture enabled. The iOS build was failing with errors like Could not build Objective‑C module 'AudioRecorderPlayer' and missing folly/Coroutine.h.

🔧 I resolved this (for now) by downgrading the package version to 3.6.14, which works fine with the current setup.

📌 Note: This is a temporary fix. I recommend downgrading only until the maintainers release an official patch that supports NitroModules and New Architecture.


npm install react-native-audio-recorder-player@3.6.14
Hope this helps anyone facing similar issues!

**Comment by noma4i** [comment]
I'm trying to install this library every few days. Looks like v4 is cursed. As for now it finally can pass `folly` issue. New issue for me is the:
```
❌  duplicate symbol 'protocol witness for Cxx.CxxPair.first.modify : A.First in conformance __C.std.__1.pair<std.__1.basic_string<CChar, std.__1.char_traits<CChar>, std.__1.allocator<CChar>>_const, std.__1.basic_string<CChar, std.__1.char_traits<CChar>, std.__1.allocator<CChar>>> : Cxx.CxxPair in __C_Synthesized' in
> libAudioRecorderPlayer.a[23](HybridAudioRecorderPlayerSpec_cxx.o)
> libReactNativeVideo.a[72](NativeVideoConfig.o)


❌  duplicate symbol 'protocol witness for Cxx.CxxPair.first.setter : A.First in conformance __C.std.__1.pair<std.__1.basic_string<CChar, std.__1.char_traits<CChar>, std.__1.allocator<CChar>>_const, std.__1.basic_string<CChar, std.__1.char_traits<CChar>, std.__1.allocator<CChar>>> : Cxx.CxxPair in __C_Synthesized' in
> libAudioRecorderPlayer.a[23](HybridAudioRecorderPlayerSpec_cxx.o)
> libReactNativeVideo.a[72](NativeVideoConfig.o)


❌  ld: 2 duplicate symbols



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
``` 

The issue comes from `react-native-audio-recorder-player` now in conflict with the `react-native-video`. Mainly because `react-native-video` is now nitro module so I think there could be some issues in the nitro modules it self.

**Comment by khuongphp** [comment]
sam issue.

**Comment by hyochan** [comment]
Would you kindly try `5.0.0-rc.1 ` by installing with `npm install react-native-audio-recorder-player@next`? Native turbomodule version is released in `next` pacakage which is being worked on in #679

**Comment by hyochan** [comment]
> AudioRecorderPlayer i issue Command SwiftCompile failed with a nonzero exit code #
> 
> <img alt="Image" width="475" height="382" src="https://private-user-images.githubusercontent.com/166438584/476441448-f55fd1a1-fea8-4e52-87ad-c83bc7203c6b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ4OTI1ODUsIm5iZiI6MTc1NDg5MjI4NSwicGF0aCI6Ii8xNjY0Mzg1ODQvNDc2NDQxNDQ4LWY1NWZkMWExLWZlYTgtNGU1Mi04N2FkLWM4M2JjNzIwM2M2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgxMVQwNjA0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2NhOGFmNjJiZGMzZDQ4ZTZlYzM3ZThiYmJlNzI1NDkzNTdhMjMyOWQ2OGI1Nzg2ZDg2MGUyNTU4ZmM5ZjBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZKa9bROSA7jlfv2-wgHesMP6RZOcbDClpI1MFqWtI7w"> <img alt="Image" width="475" height="382" src="https://private-user-images.githubusercontent.com/166438584/476441572-7fa4dd26-3606-4777-a990-2b249fab5908.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ4OTI1ODUsIm5iZiI6MTc1NDg5MjI4NSwicGF0aCI6Ii8xNjY0Mzg1ODQvNDc2NDQxNTcyLTdmYTRkZDI2LTM2MDYtNDc3Ny1hOTkwLTJiMjQ5ZmFiNTkwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgxMVQwNjA0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTU0NGMxZDQyYmI3MDIyNmVhMDI5M2NiOWQ1MGRhMmZiYWQ4MTFmZjU5YzY3MzI3ZTQzMGU4YTg0NmRkYTUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IJWK2_xYDbsX19DWVptjS_iPYQ5-AXrCPW9F7RhkILw">

Which version did you try?

**Comment by aborile** [comment]
> Would you kindly try `5.0.0-rc.1 ` by installing with `npm install react-native-audio-recorder-player@next`? Native turbomodule version is released in `next` pacakage which is being worked on in [#679](https://github.com/hyochan/react-native-audio-recorder-player/pull/679)

I have same build problem with version `^4.2.2`, and I finally can success to build with `5.0.0-rc.1` !!! @hyochan

**Comment by LjjMarster** [comment]
> > Would you kindly try `5.0.0-rc.1 ` by installing with `npm install react-native-audio-recorder-player@next`? Native turbomodule version is released in `next` pacakage which is being worked on in [#679](https://github.com/hyochan/react-native-audio-recorder-player/pull/679)
> 
> 我与`^4.2.2`版本有相同的构建问题，我终于可以用`5.0.0-rc.1`成功构建了！！！[@hyochan](https://github.com/hyochan)
> 
> +）不幸的是，我发现使用`5.0.0-rc.1`，音频播放器无法开始播放`[Error: Failed to set audio session category]`。我刚刚在README文件中使用了[示例代码](https://github.com/hyochan/react-native-audio-recorder-player?tab=readme-ov-file#audioplayer-component-with-loading-states)，并尝试播放刚刚录制的本地音频。我没有使用任何其他应用程序，包括语音备忘录、电话。
> 
> 我不知道这个问题是否是`5.0.0-rc.1`版本的问题，因为我正要安装和测试这个库。😢（在搜索这个问题时，我遇到了你的[#652](https://github.com/hyochan/react-native-audio-recorder-player/issues/652)[的评论](https://github.com/hyochan/react-native-audio-recorder-player/issues/652#issuecomment-3172856018)，所以我在这个问题的评论中添加了这个问题。）

**Comment by aborile** [comment]
> > Would you kindly try `5.0.0-rc.1 ` by installing with `npm install react-native-audio-recorder-player@next`? Native turbomodule version is released in `next` pacakage which is being worked on in [#679](https://github.com/hyochan/react-native-audio-recorder-player/pull/679)
> 
> I have same build problem with version `^4.2.2`, and I finally can success to build with `5.0.0-rc.1` !!! [@hyochan](https://github.com/hyochan)
> 
> +) Unfortunately, I found that with `5.0.0-rc.1`, Audio player fails to start playback with `[Error: Failed to set audio session category]`. I just used [example codes](https://github.com/hyochan/react-native-audio-recorder-player?tab=readme-ov-file#audioplayer-component-with-loading-states) in README file, and I tried to play local audio just recorded. I did not use any other apps, including Voice memos, phone calls.
> 
> I don't know whether this problem is an issue with version `5.0.0-rc.1` or not, since I was just about to install and test this library. 😢 (While searching about this issue, I met your [#652](https://github.com/hyochan/react-native-audio-recorder-player/issues/652) '[s comments](https://github.com/hyochan/react-native-audio-recorder-player/issues/652#issuecomment-3172856018), so I added this problem in this issue's comment.)

Oh, I just restarted my app today, and it works well ... 😂 without changing code

**Comment by mrousavy** [comment]
You need to update Nitro Modules and Nitrogen to the latest version, and re-generate specs for this library. I fixed the duplicate symbols ld error in Nitro.

**Comment by mrousavy** [comment]
Which RN version?

**Comment by aborile** [comment]
> Either you upgrade to react-native 0.80+, or we add the folly flags to the podspecs.
> 
> I guess this could fix it in Nitro; [mrousavy/nitro#825](https://github.com/mrousavy/nitro/pull/825)

Oh, It is react-native 0.79.5 😅 

Since I'm using expo 53, I have to check whether I can upgrade RN version to 0.80.
I'll try it! Thanks for letting me know 😄

**Comment by prashantBirlasoft** [comment]
I am facing same issue with 0.74.3

**Comment by hyochan** [comment]
Looks like you haven't installed `react-native-nitro-modules` as stated in https://github.com/hyochan/react-native-audio-recorder-player?tab=readme-ov-file#getting-started

**Comment by robsoden** [comment]
fwiw, I was still experiencing this problem with the following:
react-native-audio-recorder-player: 4.4.0
react-native-nitro-modules: 0.29.0
react-native: 81
I do have `use_frameworks! :linkage => :static` (for firebase)

upgrading to react-native-audio-recorder-player 5.0.0-rc.1 DID solve it, just makes me a little nervous being on next instead of stable release

**Comment by hyochan** [comment]
@robsoden The `5.0.0-rc.1` version is turbomodule version which won't be supported in the future! I think you should try PR in #686

**Comment by ahsanali274** [comment]
@hyochan I tried the changes mentioned in https://github.com/hyochan/react-native-audio-recorder-player/pull/686 by creating this patch and it is working for me.

```diff --git a/node_modules/react-native-audio-recorder-player/NitroAudioRecorderPlayer.podspec b/node_modules/react-native-audio-recorder-player/NitroAudioRecorderPlayer.podspec
index 03f0089..eb5ece4 100644
--- a/node_modules/react-native-audio-recorder-player/NitroAudioRecorderPlayer.podspec
+++ b/node_modules/react-native-audio-recorder-player/NitroAudioRecorderPlayer.podspec
@@ -1,7 +1,7 @@
 require "json"
 
 package = JSON.parse(File.read(File.join(__dir__, "package.json")))
-folly_compiler_flags = '-DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1 -Wno-comma -Wno-shorten-64-to-32'
+folly_compiler_flags = '-DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1'
 
 Pod::Spec.new do |s|
   s.name         = "NitroAudioRecorderPlayer"
@@ -28,10 +28,13 @@ Pod::Spec.new do |s|
   s.pod_target_xcconfig = {
     "SWIFT_VERSION" => "5.0",
     "SWIFT_ACTIVE_COMPILATION_CONDITIONS" => "$(inherited)",
-    "GCC_PREPROCESSOR_DEFINITIONS" => "$(inherited) FOLLY_NO_CONFIG FOLLY_MOBILE=1 FOLLY_USE_LIBCPP=1",
+    "HEADER_SEARCH_PATHS" => [
+       "${PODS_ROOT}/RCT-Folly",
+    ],
+    "GCC_PREPROCESSOR_DEFINITIONS" => "$(inherited) FOLLY_NO_CONFIG FOLLY_CFG_NO_COROUTINES",
+    "OTHER_CPLUSPLUSFLAGS" => folly_compiler_flags,
   }
   
-  s.compiler_flags = folly_compiler_flags
 
   s.dependency 'React-Core'
   s.dependency 'React-jsi'
```

I am using:

    "react-native": "0.79.6",
    "react-native-audio-recorder-player": "^4.4.0",
    "react-native-nitro-modules": "^0.29.1",
